##### The Boston data in the Tensorflow is a clean dataset and does not have any missing values

In [81]:
import tensorflow as tf

In [82]:
import numpy as np

In [83]:
!pip freeze

absl-py==0.2.2
alabaster==0.7.9
anaconda-client==1.6.0
anaconda-navigator==1.5
anaconda-project==0.4.1
appdirs==1.4.3
astor==0.7.1
astroid==1.4.9
astropy==1.3
Babel==2.3.4
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.5.3
bitarray==0.8.1
blaze==0.10.1
bokeh==0.12.4
boto==2.45.0
Bottleneck==1.2.0
cffi==1.9.1
chardet==2.3.0
chest==0.2.3
click==6.7
cloudpickle==0.2.2
clyent==1.2.2
colorama==0.3.7
comtypes==1.1.2
conda==4.5.6
configobj==5.0.6
contextlib2==0.5.4
cryptography==1.7.1
cycler==0.10.0
Cython==0.25.2
cytoolz==0.8.2
dask==0.13.0
datashape==0.5.4
decorator==4.0.11
dill==0.2.5
docutils==0.13.1
et-xmlfile==1.0.1
fastcache==1.0.2
Flask==0.12
Flask-Cors==3.0.2
future==0.16.0
gast==0.2.0
gevent==1.2.1
greenlet==0.4.11
grpcio==1.13.0
h5py==2.6.0
HeapDict==1.0.0
idna==2.2
imagesize==0.7.1
ipykernel==4.5.2
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
isort==4.2.5
itsdangerous==0.24
jdcal==1.3
jedi==0.9.0
Jinja2==2.9.4
jsonschema==2.5.1
jupyter==1.0.0
jupyter-clien

You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


### Load the dataset

In [84]:
from tensorflow.contrib.learn import datasets

In [85]:
#load_dataset is depreciated
boston=datasets.load_dataset('boston')

In [86]:
boston.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [87]:
features

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [88]:
# input_features or columns of the data set
features=np.array(boston.data)

# Actual output
prices=np.array(boston.target)

In [89]:
features

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [90]:
import pandas as pd
#df=pd.DataFrame(data=features.data[1:,1:])
#df=pd.DataFrame({'Column1':features[:,0],'Column2':features[:,1]})
df=pd.DataFrame(data=features[0:,0:])
#df=pd.DataFrame(data=features[0:,0:],                columns={'RAD','TAX','PT','B','LSTAT','CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS'})
df

0     1      2    3      4      5      6       7     8      9   \
0     0.00632  18.0   2.31  0.0  0.538  6.575   65.2  4.0900   1.0  296.0   
1     0.02731   0.0   7.07  0.0  0.469  6.421   78.9  4.9671   2.0  242.0   
2     0.02729   0.0   7.07  0.0  0.469  7.185   61.1  4.9671   2.0  242.0   
3     0.03237   0.0   2.18  0.0  0.458  6.998   45.8  6.0622   3.0  222.0   
4     0.06905   0.0   2.18  0.0  0.458  7.147   54.2  6.0622   3.0  222.0   
5     0.02985   0.0   2.18  0.0  0.458  6.430   58.7  6.0622   3.0  222.0   
6     0.08829  12.5   7.87  0.0  0.524  6.012   66.6  5.5605   5.0  311.0   
7     0.14455  12.5   7.87  0.0  0.524  6.172   96.1  5.9505   5.0  311.0   
8     0.21124  12.5   7.87  0.0  0.524  5.631  100.0  6.0821   5.0  311.0   
9     0.17004  12.5   7.87  0.0  0.524  6.004   85.9  6.5921   5.0  311.0   
10    0.22489  12.5   7.87  0.0  0.524  6.377   94.3  6.3467   5.0  311.0   
11    0.11747  12.5   7.87  0.0  0.524  6.009   82.9  6.2267   5.0  311.0   
12    0.09378  12.5   7.87  0.0  0.524  5.889   39.0  5.4509   5.0  311.0   
13    0.62976   0.0   8.14  0.0  0.538  5.949   61.8  4.7075   4.0  307.0   
14    0.63796   0.0   8.14  0.0  0.538  6.096   84.5  4.4619   4.0  307.0   
15    0.62739   0.0   8.14  0.0  0.538  5.834   56.5  4.4986   4.0  307.0   
16    1.05393   0.0   8.14  0.0  0.538  5.935   29.3  4.4986   4.0  307.0   
17    0.78420   0.0   8.14  0.0  0.538  5.990   81.7  4.2579   4.0  307.0   
18    0.80271   0.0   8.14  0.0  0.538  5.456   36.6  3.7965   4.0  307.0   
19    0.72580   0.0   8.14  0.0  0.538  5.727   69.5  3.7965   4.0  307.0   
20    1.25179   0.0   8.14  0.0  0.538  5.570   98.1  3.7979   4.0  307.0   
21    0.85204   0.0   8.14  0.0  0.538  5.965   89.2  4.0123   4.0  307.0   
22    1.23247   0.0   8.14  0.0  0.538  6.142   91.7  3.9769   4.0  307.0   
23    0.98843   0.0   8.14  0.0  0.538  5.813  100.0  4.0952   4.0  307.0   
24    0.75026   0.0   8.14  0.0  0.538  5.924   94.1  4.3996   4.0  307.0   
25    0.84054   0.0   8.14  0.0  0.538  5.599   85.7  4.4546   4.0  307.0   
26    0.67191   0.0   8.14  0.0  0.538  5.813   90.3  4.6820   4.0  307.0   
27    0.95577   0.0   8.14  0.0  0.538  6.047   88.8  4.4534   4.0  307.0   
28    0.77299   0.0   8.14  0.0  0.538  6.495   94.4  4.4547   4.0  307.0   
29    1.00245   0.0   8.14  0.0  0.538  6.674   87.3  4.2390   4.0  307.0   
..        ...   ...    ...  ...    ...    ...    ...     ...   ...    ...   
476   4.87141   0.0  18.10  0.0  0.614  6.484   93.6  2.3053  24.0  666.0   
477  15.02340   0.0  18.10  0.0  0.614  5.304   97.3  2.1007  24.0  666.0   
478  10.23300   0.0  18.10  0.0  0.614  6.185   96.7  2.1705  24.0  666.0   
479  14.33370   0.0  18.10  0.0  0.614  6.229   88.0  1.9512  24.0  666.0   
480   5.82401   0.0  18.10  0.0  0.532  6.242   64.7  3.4242  24.0  666.0   
481   5.70818   0.0  18.10  0.0  0.532  6.750   74.9  3.3317  24.0  666.0   
482   5.73116   0.0  18.10  0.0  0.532  7.061   77.0  3.4106  24.0  666.0   
483   2.81838   0.0  18.10  0.0  0.532  5.762   40.3  4.0983  24.0  666.0   
484   2.37857   0.0  18.10  0.0  0.583  5.871   41.9  3.7240  24.0  666.0   
485   3.67367   0.0  18.10  0.0  0.583  6.312   51.9  3.9917  24.0  666.0   
486   5.69175   0.0  18.10  0.0  0.583  6.114   79.8  3.5459  24.0  666.0   
487   4.83567   0.0  18.10  0.0  0.583  5.905   53.2  3.1523  24.0  666.0   
488   0.15086   0.0  27.74  0.0  0.609  5.454   92.7  1.8209   4.0  711.0   
489   0.18337   0.0  27.74  0.0  0.609  5.414   98.3  1.7554   4.0  711.0   
490   0.20746   0.0  27.74  0.0  0.609  5.093   98.0  1.8226   4.0  711.0   
491   0.10574   0.0  27.74  0.0  0.609  5.983   98.8  1.8681   4.0  711.0   
492   0.11132   0.0  27.74  0.0  0.609  5.983   83.5  2.1099   4.0  711.0   
493   0.17331   0.0   9.69  0.0  0.585  5.707   54.0  2.3817   6.0  391.0   
494   0.27957   0.0   9.69  0.0  0.585  5.926   42.6  2.3817   6.0  391.0   
495   0.17899   0.0   9.69  0.0  0.585  5.670   28.8  2.7986   6.0  391.0   
496   0

In [91]:
features.shape

(506, 13)

In [92]:
prices.shape

(506,)

In [93]:
prices=np.reshape(prices,(prices.shape[0],1))

In [94]:
features[0:1]

array([[6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
        6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
        4.980e+00]])

In [95]:
prices.shape

(506, 1)

In [96]:
print ('Input features shape',features.shape)
print ('Actual prices shape',prices.shape)

Input features shape (506, 13)
Actual prices shape (506, 1)


### Build the graph

#### Input placeholders

In [113]:
#Define the input place holder

In [114]:
#input placeholder for the input features , None refers to any number of rows
x=tf.placeholder(shape=[None,features.shape[1]],dtype=tf.float32,name='x-input')

In [115]:
#placeholder for the actual prices 
y_=tf.placeholder(shape=[None,prices.shape[1]],dtype=tf.float32,name='y-input')

In [116]:
# normalize the features using x min max method
x_n=tf.nn.l2_normalize(x,1)

#### Define Wieghts and Bais

In [117]:
#variable for the wieghts 
w=tf.Variable(tf.zeros(shape=[features.shape[1],1]),name='Weights')

In [118]:
#variable for the bios 
b=tf.Variable(tf.zeros(shape=[1]),name='Bais')

#### Prediction
##### Make sure the data is normalized

In [119]:
#y=xw+b

In [120]:
#The tf.matmul() op requires that both of its inputs are matrices (i.e. 2-D tensors)*, 
#and doesn't perform any automatic conversion. 
# check the dimnension of the x and w
print ('The dimension of x is',x.shape,' and of that w  is',w.shape)

The dimension of x is (?, 13)  and of that w  is (13, 1)


In [121]:
y=tf.add(tf.matmul(x_n,w),b,name='output') # changed from x to x_n

In [122]:
#I tried to print the output of matrixx multiplication. The below is the error
### You must feed a value for placeholder tensor 'x-input_1' with dtype float and shape [?,13]
#with tf.Session() as sess:
 #   print(sess.run(y))

#### Loss(Cost function)

In [123]:
#Mean squared error
# (The predicted - the actual)^2
loss=tf.reduce_mean(tf.square(y-y_),name='Loss')

In [124]:
#### Gradient Descent Optimizer to minimize loss
#learn_rate
learn_rate=0.3 # first value .03, second 0.3

In [125]:
train_op=tf.train.GradientDescentOptimizer(learn_rate).minimize(loss)

#### Log the training loss

In [126]:
training_loss=tf.summary.scalar('train_loss',loss)

#### Save the loss

In [127]:
log_dir='/tmp/boston/v2'

### Execute the Graph

In [128]:
# start the tensorlfow session
with tf.Session() as sess:
    #intialize the variables before we start
    sess.run(tf.global_variables_initializer())
   
    #Displaying of the data
    training_epochs=1000
    
    #logging and saving the graph
    saver=tf.train.Saver()
    writer=tf.summary.FileWriter(log_dir,graph=tf.get_default_graph())
    
    for i in range(training_epochs):
        #calculate the train_op and loss
        train_model,train_loss,log_loss=sess.run([train_op,loss,training_loss],
                                                 #execute the train_op (GradientDescentOptimizer) and loss
                              feed_dict=({x:features,#data for input features
                                        y_:prices}))# actual prices data
                
        writer.add_summary(log_loss,i)
            #print i after every 10 iterations
        if i%100==0:
            print ('The loss at ',i,' is ',train_loss)
    
    #saave the graph
    saver.save(sess,log_dir + '/' + 'Boston.ckpt')
                

The loss at  0  is  592.1469
The loss at  100  is  62.925106
The loss at  200  is  61.639965
The loss at  300  is  60.64175
The loss at  400  is  59.84187
The loss at  500  is  59.183147
The loss at  600  is  58.625904
The loss at  700  is  58.142456
The loss at  800  is  57.713425
The loss at  900  is  57.3251


UnknownError: Failed to rename: /tmp/boston/v2/Boston.ckpt.index.tempstate6186423970516491866 to: /tmp/boston/v2/Boston.ckpt.index : Access is denied.
; Input/output error
	 [[Node: save_2/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_2/Const_0_0, save_2/SaveV2/tensor_names, save_2/SaveV2/shape_and_slices, Bais, Bais_1, Bais_2, Weights, Weights_1, Weights_2)]]

Caused by op 'save_2/SaveV2', defined at:
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\ipykernel\__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\ipykernel\kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\tornado\ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\ipykernel\kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\ipykernel\kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\ipykernel\kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\ipykernel\zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-128-f078b9b974b9>", line 10, in <module>
    saver=tf.train.Saver()
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\tensorflow\python\training\saver.py", line 1284, in __init__
    self.build()
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\tensorflow\python\training\saver.py", line 1296, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\tensorflow\python\training\saver.py", line 1333, in _build
    build_save=build_save, build_restore=build_restore)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\tensorflow\python\training\saver.py", line 778, in _build_internal
    save_tensor = self._AddSaveOps(filename_tensor, saveables)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\tensorflow\python\training\saver.py", line 278, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\tensorflow\python\training\saver.py", line 194, in save_op
    tensors)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1800, in save_v2
    shape_and_slices=shape_and_slices, tensors=tensors, name=name)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "D:\Mallikarjun\UPXAcademylearning\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnknownError (see above for traceback): Failed to rename: /tmp/boston/v2/Boston.ckpt.index.tempstate6186423970516491866 to: /tmp/boston/v2/Boston.ckpt.index : Access is denied.
; Input/output error
	 [[Node: save_2/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_2/Const_0_0, save_2/SaveV2/tensor_names, save_2/SaveV2/shape_and_slices, Bais, Bais_1, Bais_2, Weights, Weights_1, Weights_2)]]


### how to view in Tensor board

In [ ]:
#tensorboard -logdir=/temp/Boston

### Predictions

In [ ]:
input_data=features[0:1]
input_data

In [ ]:
with tf.Session() as sess:
    prediction=sess.run([y],feed_dict={x:input_data})
    print("Price is :",prediction)