## numpy.arange() in Python

### About : 
https://www.geeksforgeeks.org/numpy-arange-python/

arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval. The interval mentioned is half opened i.e. [Start, Stop)

start : [optional] start of interval range. By default start = 0

stop  : end of interval range

step  : [optional] step size of interval. By default step size = 1,  

For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. 

dtype : type of output array

In [2]:
import numpy as np
 
print("A\n", np.arange(4).reshape(2, 2), "\n")
 
print("A\n", np.arange(4, 10), "\n")
 
print("A\n", np.arange(4, 20, 3), "\n")

A
 [[0 1]
 [2 3]] 

A
 [4 5 6 7 8 9] 

A
 [ 4  7 10 13 16 19] 

